#!/usr/bin/php
<?php
//TestTech86 support@cymdev.com
date_default_timezone_set('Europe/Paris');
require 'php-mime-mail-parser-master/vendor/autoload.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;

require 'PHPMailer/src/Exception.php';
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';


/**
 * 
 */
class logToFile
{
  static $_folderSave;
  static $_retry = 3;

  static function errorHandler($errno, $errstr, $errfile, $errline)
  {
     if (!(error_reporting() & $errno)) {
          // Ce code d'erreur n'est pas inclus dans error_reporting(), donc il continue
          // jusqu'au gestionaire d'erreur standard de PHP
          return;
      }

      switch ($errno) {
      case E_USER_ERROR:
          self::logToCli("[$errno] $errstr Erreur fatale sur la ligne $errline dans le fichier $errfile");
          self::logToCli("Arrêt...\n");
          exit(1);
          break;

      case E_USER_WARNING:
          self::logToCli("[$errno] $errstr ALERTE sur la ligne $errline dans le fichier $errfile");
          self::logToCli("Arrêt...\n");
          exit(1);
          break;

      case E_USER_NOTICE:
          self::logToCli("[$errno] $errstr AVERTISSEMENT sur la ligne $errline dans le fichier $errfile");
          break;

      default:
          self::logToCli("[$errno] $errstr AVERTISSEMENT sur la ligne $errline dans le fichier $errfile");
          break;
      }

      /* Ne pas exécuter le gestionnaire interne de PHP */
      return true;
  }

  static function logToCli($text)
  {
    echo "$text\n";
    $logLine = "[".date('d/m/y H:i:s')."] : $text\n";
    if (file_exists(self::$_folderSave.'/archiver.log')) {
      file_put_contents(self::$_folderSave.'/archiver.log', $logLine, FILE_APPEND);
    }
  }
}

$error_handler = set_error_handler(array("logToFile", "errorHandler"));

/**
 * 
 */
class Support
{
	private $_server;
	private $_imapRessource;
	private $_mailBoxes;
	private $_user;
	private $_baseTo;
	private $_config;
	private $_ticket;
	private $_hS;
	private $_bBox;
	private $_INBOX;
	private const ALTERNATIVE_HS_CHAR = '='; 

	function __construct($config)
	{
		

		$this->_config = $config;
		$this->makeConfig();
		$this->getMailBoxes();
	    $this->parseTicket();

	    var_dump($this->_ticket);
	    exit();
	}

	function __destruct()
	{
	  	imap_expunge($this->_imapRessource);
	    var_dump(imap_errors()); 
	    imap_close($this->_imapRessource, CL_EXPUNGE);
	}

	private function makeConfig()
	{
		$this->_server = $this->_config['IMAP']['server'];
	    $this->_user = $this->_config['IMAP']['user'];
	    $this->_baseTo = explode('@', $this->_user)[0].'+';
	    $this->_hS = $this->_config['IMAP']['hierarchySeparator'];
	    $this->_bBox = $this->_config['IMAP']['baseBox'];
	    $this->_INBOX = $this->_server.$this->_bBox;

	    $this->_imapRessource = imap_open(
	    			$this->_server, 
	    			$this->_user, 
	    			$this->_config['IMAP']['password'], 
	    			NULL, 
	    			3, 
	    			array('DISABLE_AUTHENTICATOR' => 'GSSAPI')
	    		) or die("can't connect: " . imap_last_error());

	    $this->_server .= $this->_bBox.$this->_hS;

	   	logToFile::$_folderSave = "./".$this->_config['IMAP']['server'];
	   	imap_expunge($this->_imapRessource);
	}

	private function getMailBoxes()
	{
		$this->_mailBoxes = imap_list($this->_imapRessource, $this->_server, '*');
		var_dump($this->_mailBoxes);
	}

	private function sendMail($from, $to, $subject, $textMessage)
	{
		//exit();
		$mail = new PHPMailer(true);
		$mail->CharSet = 'UTF-8';
		try {
		    //Server settings
		    $mail->SMTPDebug = 0;                      // Enable verbose debug output
		    $mail->isSMTP();                                            // Send using SMTP
		    $mail->Host       = $this->_config['SMTP']['host'];         // Set the SMTP server to send through
		    $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
		    $mail->Username   = $this->_config['SMTP']['user'];         // SMTP username
		    $mail->Password   = $this->_config['SMTP']['password'];     // SMTP password
		    $mail->SMTPSecure = 'tls';         // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` also accepted
		    $mail->Port       = $this->_config['SMTP']['port'];         // TCP port to connect to

		    //Recipients
		    $mail->setFrom($this->_config['SUPPORT']['email'], $this->_config['SUPPORT']['senderName']);
		    if (is_array($to)) {
		    	foreach ($to as $key => $value) {
		    		$mail->addAddress($value);
		    	}
		    } else {
		    	$mail->addAddress($to);
		    }
		                   // Name is optional
		    
		    $mail->addReplyTo($from, $this->_config['SUPPORT']['senderName']);

		    // Content
		    $mail->isHTML(true);                                  // Set email format to HTML
		    $mail->Subject = $subject;
		    $mail->Body    = $textMessage;
		    $mail->AltBody = strip_tags(str_replace('<br>', "\n", $textMessage));

		    $mail->send();
		    
		} catch (Exception $e) {
		    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
		}
	}

	private function parseTicket()
	{
		$ticketFolderExist = false;

	    foreach ($this->_mailBoxes as $key => $mailBoxe) {
	    	$this->_mailBoxes[$key] = str_replace($this->_server, '', $mailBoxe);
	    	if ($this->_mailBoxes[$key] == 'TICKET') {
	    		$ticketFolderExist = true;
	    	}
	    }

	    if (!$ticketFolderExist) {
	    	imap_createmailbox($this->_imapRessource, $this->_server.'TICKET');	    	
	    }

		echo "Récupération des ticket existant \n";

		$ticket = array();
		foreach ($this->_mailBoxes as $mailBoxe) {
			if (substr($mailBoxe, 0, 7) == 'TICKET'.$this->_hS) {
				$ticketArray = explode($this->_hS, $mailBoxe);
				$ticketData = explode('_', $ticketArray[1]);
				if (substr($ticketData[0], 0, 5) == 'CLOS-') {
					$ticketNumber = intval(str_replace('CLOS-', '', $ticketData[0]));
					$ticketState = 'CLOSE';
				} else {
					$ticketNumber = intval($ticketData[0]);
					$ticketState = 'OPEN';
				}
				if (!isset($ticketData[1])) {
					$ticketData[1] = '';
				}
				
				if (!isset($ticket[$ticketNumber])) {
					$ticket[$ticketNumber] = ['email' => array(), 'subject' => $ticketData[1], 'mailboxe' => $mailBoxe, 'state' => $ticketState];
					
					if (count($ticketArray) > 2) {
						$ticket[$ticketNumber]['email'][] = str_replace($this::ALTERNATIVE_HS_CHAR, $this->_hS, $ticketArray[2]);
					}
				} else {
					if (count($ticketArray) > 2) {
						$ticket[$ticketNumber]['email'][] = str_replace($this::ALTERNATIVE_HS_CHAR, $this->_hS, $ticketArray[2]);
					}
				}
			}
		}
		$this->_ticket = $ticket;
	}

	private function getNewMail()
	{
		echo "Lecture des nouveaux e-mail \n";
		imap_reopen($this->_imapRessource, $this->_INBOX);

		$count = imap_num_msg($this->_imapRessource);
    	logToFile::logToCli("$count message a traité.");
    	$uids = imap_search($this->_imapRessource, 'ALL', SE_UID, "UTF-8");
    	
    	if (!$uids) return;
    	foreach ($uids as $ud) {
    		$k = imap_msgno ($this->_imapRessource, $ud);  
        	$body=imap_fetchbody($this->_imapRessource, $k, "");
        	$Parser = new PhpMimeMailParser\Parser();
		    $Parser->setText($body);
		    $mailArray = array();
		    $mailArray['from'] = $Parser->getHeader('from');
		    $mailArray['to'] = mailparse_rfc822_parse_addresses($Parser->getHeader('To'));
		    $textMessage = $Parser->getMessageBody('html');
		    $subject = $Parser->getHeader('Subject');
		    $action = 0;
		    $ticketNumber = 0;
		    if (is_array($mailArray['to']) && count($mailArray['to']) > 0) {
		    	foreach ($mailArray['to'] as $mailTo) {
		    		$supportDomain = explode('@', $this->_config['SUPPORT']['email'])[1];
		    		$supportUser = explode('@', $this->_config['SUPPORT']['email'])[0];
		    		$mailToDomain = explode('@', $mailTo['address'])[1];
		    		$mailToUser = explode('@', $mailTo['address'])[0];

		    		$ticketNumber = $this->isExistingTicket($mailTo['address'], $subject);
		    		

		    		if ($ticketNumber === false && $mailTo['address'] == $this->_config['SUPPORT']['email']) {
		    			// new ticket
		    			if ($action == 0) {
		    				$action = 1;
		    			}
		    		} elseif ($supportDomain == $mailToDomain && is_int($ticketNumber) && $ticketNumber !== false) 
		    		{
		    			if (isset($this->_ticket[$ticketNumber]) && $this->_ticket[$ticketNumber]['state'] == 'OPEN')
		    			{
		    				if (isset($this->_config['SUPPORT']['sendAdmin']) 
		    						&& in_array(
		    							mailparse_rfc822_parse_addresses($mailArray['from'])[0]['address'],
		    							$this->_config['SUPPORT']['sendAdmin'])
		    						&& count($mailArray['to']) > 1) {
		    					$action = 3;
		    					//var_dump($mailArray['to']);
		    				} else {
		    					$action = 2;
		    				}
		    			} elseif(isset($this->_ticket[$ticketNumber]) && $this->_ticket[$ticketNumber]['state'] !== 'OPEN') {
		    				$action = 4;
		    			}
		    			
		    		}
		    	}
		    }

		    echo "$k : ";
		    switch ($action) {
		    	case 0:
		    		$this->errorMessage($k);
		    		break;
		    	case 1:
		    		$this->newTicket($mailArray['from'], $k, $textMessage, $subject);
		    		break;
		    	case 2:
		    		$this->forwardToTicket($mailArray['from'], $ticketNumber, $k, $textMessage);
		    		break;
		    	case 3:
		    		$this->addEmailToTicket($ticketNumber, $mailArray['to'], $k);
		    		break;
		    	case 4:
		    		$this->clotureTicket($ticketNumber, $textMessage, $mailArray['from'], $k);
		    		break;
		    	default:
		    		# code...
		    		break;
		    }
    	}
	}

	private function getNewTicketNumber()
	{
		$max = 0;
		foreach ($this->_ticket as $key => $value) {
			if ($key>$max) {
				$max = $key;
			}
		}

		return $max+1;
	}

	private function getTicketAddress($ticketNumber)
	{
		if ($this->_config['SUPPORT']['filterBy'] == 'address') {
			return str_replace('@', "+$ticketNumber@", $this->_config['SUPPORT']['email']);
		} else {
			return $this->_config['SUPPORT']['email'];
		}
	}

	private function isExistingTicket($dest, $subject)
	{
		$supportDomain = explode('@', $this->_config['SUPPORT']['email'])[1];
		$supportUser = explode('@', $this->_config['SUPPORT']['email'])[0];
		$mailToDomain = explode('@', $dest)[1];
		$mailToUser = explode('@', $dest)[0];

		if ($this->_config['SUPPORT']['filterBy'] == 'address') {
			if ($mailTo['address'] == $this->_config['SUPPORT']['email']) {
				return false;
			} elseif ($supportDomain == $mailToDomain) {
		    	$mailToUserBase = explode('+', $mailToUser);
		    	if (strtolower($mailToUserBase[0]) == strtolower($supportUser)) {
		    		if (isset($this->_ticket[$mailToUserBase[1]])) return $mailToUserBase[1];
		    	}
		    }
		} else {
			if (strpos($subject, "[TICKET#") === false) {
				return false;
			} else {
				$ticketNumber = intval(explode(']', explode('[TICKET#', ' '.$subject)[1])[0]);
				if (isset($this->_ticket[$ticketNumber])) return $ticketNumber;
			}
		}

		return false;
	}

	private function createMailBoxName($text)
	{
		$text = str_replace($this->_hS, $this::ALTERNATIVE_HS_CHAR, $text);
		$encoding = mb_detect_encoding($text);
		return mb_convert_encoding($text,"UTF7-IMAP",$encoding);
	}


	private function addEmailToTicket($ticketNumber, $toArray, $msgNumber)
	{
		echo "Ajout d'un destinataire au ticket $ticketNumber \n";
		$ticketAddress = explode('@', $this->_config['SUPPORT']['email'])[0].'+'.$ticketNumber.'@'.explode('@', $this->_config['SUPPORT']['email'])[1];
		foreach ($toArray as $key => $value) {
			if ($value['address'] != $ticketAddress && !in_array($value['address'], $this->_ticket[$ticketNumber]['email'])) {
				$value['address'] = createMailBoxName($value['address']);
				imap_createmailbox($this->_imapRessource, $this->_server.$this->_ticket[$ticketNumber]['mailboxe'].$this->_config['IMAP']['hierarchySeparator'].$value['address']);
			}
		}
		imap_mail_move ($this->_imapRessource , "$msgNumber:$msgNumber" , $this->_ticket[$ticketNumber]['mailboxe']);
	}

	private function newTicket($from, $msgNumber, $textMessage, $subject)
	{
		echo "Nouveau Ticket \n";
		$subject = str_replace('_', '-', $subject);
		$ticketNumber = $this->getNewTicketNumber();
		$ticketMailBoxe = $ticketNumber.'_'.$subject;
		$ticketMailBoxe = $this->createMailBoxName($ticketMailBoxe);
		$fromEmail = mailparse_rfc822_parse_addresses($from);
		if (count($fromEmail) > 0 && isset($fromEmail[0]['address'])) {
			echo "nouveau ticket : $ticketNumber \n";
			imap_createmailbox($this->_imapRessource, $this->_server.'TICKET'.$this->_config['IMAP']['hierarchySeparator'].$ticketMailBoxe);
			$destAdress = $this->createMailBoxName($fromEmail[0]['address']);
			imap_createmailbox($this->_imapRessource, $this->_server.'TICKET'.$this->_config['IMAP']['hierarchySeparator'].$ticketMailBoxe.$this->_config['IMAP']['hierarchySeparator'].$destAdress);
			
			echo $this->_server.'TICKET'.$this->_config['IMAP']['hierarchySeparator'].$ticketMailBoxe." \n";


			$ticketAddress = $this->getTicketAddress($ticketNumber);

			$message = str_replace('{TICKETNUMBER}', $ticketNumber, $this->_config['SUPPORT']['newTicketMessage']);
			$message = str_replace('{TICKETADDRESS}', $ticketAddress, $message);
			
			if ($this->_config['SUPPORT']['includeAllMessage'] == 1) {
				$message .= '<hr>'.$textMessage;
			}

			$this->sendMail($ticketAddress, $fromEmail[0]['address'], "[TICKET#$ticketNumber] $subject", $message);
			imap_mail_move ($this->_imapRessource , "$msgNumber:$msgNumber" , 'TICKET'.$this->_config['IMAP']['hierarchySeparator'].$ticketMailBoxe);
			if (isset($this->_config['SUPPORT']['sendAdmin'])) {
				$adminMessage = str_replace('{TICKETNUMBER}', $ticketNumber, $this->_config['SUPPORT']['newTicketAdminMessage']).'<hr>'.$textMessage;
				$this->sendMail($ticketAddress, $this->_config['SUPPORT']['sendAdmin'], "[TICKET#$ticketNumber] $subject", $adminMessage);
			}
		}
		
	}

	private function errorMessage($msgNumber)
	{
		//var_dump($this->_mailBoxes);
		if (!in_array($this->_config['SUPPORT']['onError'], $this->_mailBoxes)) {
			echo "Création du dossier  : ".$this->_config['SUPPORT']['onError']." \n";
			imap_createmailbox($this->_imapRessource, $this->_server.$this->_config['SUPPORT']['onError']);
		}
		
		echo "Message incorrect a déplacer vers : ".$this->_config['SUPPORT']['onError']." \n";
		imap_mail_move ($this->_imapRessource , "$msgNumber:$msgNumber" ,$this->_config['SUPPORT']['onError']);
	}

	private function forwardToTicket($from, $ticketNumber, $msgNumber, $textMessage)
	{
		echo "Message a transférer au destinataire du ticket $ticketNumber \n";
		$from = mailparse_rfc822_parse_addresses($from);
		$exist = 0;
		$ticketEndMail = str_replace('@', "+CLORE-$ticketNumber@", $this->_config['SUPPORT']['email']);
		$footer = $this->getTemplate('footerMessage', ['TICKETCLOTUREADDRESS' => $ticketEndMail]);
		$textMessage = '<b>'.$from[0]['display'].' : </b><br><br>'.$textMessage.$footer;
		
		if (in_array($from[0]['address'], $this->_ticket[$ticketNumber]['email']) 
			|| in_array($from[0]['address'], $this->_config['SUPPORT']['sendAdmin'])) {
			$exist = 1;
			$send = 0;
			$fromEmail = explode('@', $this->_config['SUPPORT']['email'])[0].'+'.$ticketNumber.'@'.explode('@', $this->_config['SUPPORT']['email'])[1];
			$subject = $this->_ticket[$ticketNumber]['subject'];
			foreach ($this->_ticket[$ticketNumber]['email'] as $destEmail) {
				if ($destEmail !== $from[0]['address']) {
					echo "\ttransfert vers : $destEmail \n";
					$this->sendMail($fromEmail, $destEmail, "[TICKET#$ticketNumber] $subject", $textMessage);
					$send++;
				}
			}
			if ($send == 0) {
				$destEmail = $this->_config['SUPPORT']['sendAdmin'];
				echo "\ttransfert vers administrateur : Admin \n";
				$this->sendMail($fromEmail, $destEmail, "[TICKET#$ticketNumber] $subject", $textMessage);
			}
			imap_mail_move ($this->_imapRessource , "$msgNumber:$msgNumber" , $this->_ticket[$ticketNumber]['mailboxe']);
		}
		if ($exist == 0) {
			imap_delete($this->_imapRessource , $msgNumber);
		}
	}

	private function clotureTicket($ticketNumber, $textMessage, $from, $msgNumber)
	{
		echo "Cloture du ticket $ticketNumber \n";
		$from = mailparse_rfc822_parse_addresses($from);
		$exist = 0;
		$textMessage = $this->_config['SUPPORT']['clotureMessage'].'<b>'.$from[0]['display'].' : </b><br><br>'.$textMessage;
		if (in_array($from[0]['address'], $this->_ticket[$ticketNumber]['email'])) {
			$exist = 1;
			foreach ($this->_ticket[$ticketNumber]['email'] as $destEmail) {
					echo "\ttransfert vers : $destEmail \n";
					$fromEmail = explode('@', $this->_config['SUPPORT']['email'])[0].'+'.$ticketNumber.'@'.explode('@', $this->_config['SUPPORT']['email'])[1];
					$subject = $this->_config['SUPPORT']['clotureSubject'];
					$this->sendMail($fromEmail, $destEmail, "[TICKET#$ticketNumber] $subject", $textMessage);
			}
			imap_mail_move ($this->_imapRessource , "$msgNumber:$msgNumber" , $this->_ticket[$ticketNumber]['mailboxe']);
			imap_renamemailbox ($this->_imapRessource , $this->_server.$this->_ticket[$ticketNumber]['mailboxe'], $this->_server.str_replace('TICKET'.$this->_config['IMAP']['hierarchySeparator'], 'TICKET'.$this->_config['IMAP']['hierarchySeparator'].'CLOS-', $this->_ticket[$ticketNumber]['mailboxe']));
		}

		if ($exist == 0) {
			imap_delete($this->_imapRessource , $msgNumber);
		}
		
	}

	private function getTemplate($template, $data)
	{
		$templateTxt = "UNKNOW TEMPLATE";
		if (isset($this->_config['SUPPORT'][$template])) {
			$templateTxt = $this->_config['SUPPORT'][$template];
		}
		foreach ($data as $key => $value) {
			$templateTxt = str_replace("{".$key."}", $value, $templateTxt);
		}

		return $templateTxt;

	}

	public function clean($message)
	{

	}

	public function cron()
	{
		$this->getNewMail();
	}

	public function dispHelp()
	{
		echo "Aide : \n";
	}

	public function dispTicket()
	{
		//var_dump($this->_ticket);
		foreach ($this->_ticket as $key => $value) {
			echo "$key\temail\t\t".$value['state']."\t".$value['subject']."\n";
			foreach ($value['email'] as $email) {
				echo "\t$email\n";
			}
			echo "\n";
		}
	}
}



if (!isset($argv[1])) {
  $iniFile = scandir('./');
  foreach ($iniFile as $key => $value) {
  	if (substr($value, -4) == '.ini') {
  		echo "Fichier de configuration : $value\n";
  		$accountConfig = parse_ini_file ($value,TRUE);
  		$support = new Support($accountConfig);
  		$support->cron();
  	}
  }

} else {
	$iniFile = $argv[1].'.ini';
	$accountConfig = parse_ini_file ($iniFile,TRUE);
	$retry = 0;
	$state = false;

	$support = new Support($accountConfig);
	if (!isset($argv[2])) {
		$support->cron();
	} else {
		switch ($argv[2]) {
			case 'cron':
				$support->cron();
				break;
			
			case 'help':
				$support->dispHelp();
				break;

			case 'list':
				$support->dispTicket();
				break;
			
			default:
				echo "Usage : cymSupport [account] [command]\n";
				break;
		}
	}
}



